import { skillIcons } from '../assets';
import type { CarouselIcon } from '../interfaces';

export const carouselIcons: CarouselIcon[] = [
  {
    id: 1,
    src: skillIcons.git,
    alt: 'Git',
    summary: 'skills.carouselSummaries.git',
    doc: 'https://git-scm.com/doc',
  },
  {
    id: 2,
    src: skillIcons.html,
    alt: 'HTML',
    summary: 'skills.carouselSummaries.html',
    doc: 'https://developer.mozilla.org/docs/Web/HTML',
  },
  {
    id: 3,
    src: skillIcons.css,
    alt: 'CSS',
    summary: 'skills.carouselSummaries.css',
    doc: 'https://developer.mozilla.org/docs/Web/CSS',
  },
  {
    id: 4,
    src: skillIcons.javascript,
    alt: 'JavaScript',
    summary: 'skills.carouselSummaries.javascript',
    doc: 'https://developer.mozilla.org/docs/Web/JavaScript',
  },
  {
    id: 5,
    src: skillIcons.react,
    alt: 'ReactJS',
    summary: 'skills.carouselSummaries.react',
    doc: 'https://reactjs.org/docs',
  },
  {
    id: 6,
    src: skillIcons.vuejs,
    alt: 'VueJS',
    summary: 'skills.carouselSummaries.vuejs',
    doc: 'https://vuejs.org/v2/guide/',
  },
  {
    id: 7,
    src: skillIcons.redux,
    alt: 'Redux',
    summary: 'skills.carouselSummaries.redux',
    doc: 'https://redux.js.org/introduction/getting-started',
  },
  {
    id: 8,
    src: skillIcons.jest,
    alt: 'Jest',
    summary: 'skills.carouselSummaries.jest',
    doc: 'https://jestjs.io/docs/en/getting-started',
  },
  {
    id: 9,
    src: skillIcons.testingLibrary,
    alt: 'Testing Library',
    summary: 'skills.carouselSummaries.testingLibrary',
    doc: 'https://testing-library.com/docs/',
  },
  {
    id: 10,
    src: skillIcons.typescript,
    alt: 'TypeScript',
    summary: 'skills.carouselSummaries.typescript',
    doc: 'https://www.typescriptlang.org/docs/',
  },
  {
    id: 11,
    src: skillIcons.docker,
    alt: 'Docker',
    summary: 'skills.carouselSummaries.docker',
    doc: 'https://docs.docker.com/',
  },
  {
    id: 12,
    src: skillIcons.nodejs,
    alt: 'Node.js',
    summary: 'skills.carouselSummaries.nodejs',
    doc: 'https://nodejs.org/en/docs/',
  },
  {
    id: 13,
    src: skillIcons.golang,
    alt: 'Go',
    summary: 'skills.carouselSummaries.golang',
    doc: 'https://golang.org/doc/',
  },
  {
    id: 14,
    src: skillIcons.java,
    alt: 'Java',
    summary: 'skills.carouselSummaries.java',
    doc: 'https://docs.oracle.com/en/java/',
  },
  {
    id: 15,
    src: skillIcons.python,
    alt: 'Python',
    summary: 'skills.carouselSummaries.python',
    doc: 'https://docs.python.org/3/',
  },
  {
    id: 16,
    src: skillIcons.mysql,
    alt: 'MySQL',
    summary: 'skills.carouselSummaries.mysql',
    doc: 'https://dev.mysql.com/doc/',
  },
  {
    id: 17,
    src: skillIcons.mongodb,
    alt: 'MongoDB',
    summary: 'skills.carouselSummaries.mongodb',
    doc: 'https://docs.mongodb.com/',
  },
  {
    id: 18,
    src: skillIcons.linux,
    alt: 'Linux',
    summary: 'skills.carouselSummaries.linux',
    doc: 'https://www.linux.org/docs/',
  },
  {
    id: 19,
    src: skillIcons.dotnet,
    alt: '.NET',
    summary: 'skills.carouselSummaries.dotnet',
    doc: 'https://learn.microsoft.com/dotnet/',
  },
  {
    id: 20,
    src: skillIcons.vitest,
    alt: 'Vitest',
    summary: 'skills.carouselSummaries.vitest',
    doc: 'https://vitest.dev/',
  },
];
